import { defineArrayMember, defineField, defineType } from 'sanity'

export default defineType({
  name: 'landingPage',
  title: 'Landing Page / 首頁設定',
  type: 'document',
  groups: [
    { name: 'hero', title: 'Hero', default: true },
    { name: 'whoWeAre', title: 'Who We Are / 我們是誰' },
    { name: 'articles', title: 'Featured Articles / 精選文章' },
    { name: 'cta', title: 'Bottom CTA / 底部 CTA' },
  ],
  fields: [
    defineField({
      name: 'heroBackgroundImage',
      title: 'Hero Background / Hero 背景圖',
      type: 'image',
      group: 'hero',
      options: { hotspot: true },
      description: '首頁主視覺背景。建議使用寬幅、情緒感較強的照片。',
      fields: [
        defineField({
          name: 'alt',
          title: 'Alt Text / 圖片替代文字',
          type: 'string',
        }),
      ],
    }),
    defineField({
      name: 'heroEyebrow',
      title: 'Hero Eyebrow / 上方小標',
      type: 'string',
      group: 'hero',
      initialValue: 'Chiangway Travel in Chiang Mai',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'heroTitle',
      title: 'Hero Title / 主標題',
      type: 'string',
      group: 'hero',
      initialValue: '爸媽開的清邁親子包車',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'heroSubtitle',
      title: 'Hero Subtitle / 副標',
      type: 'string',
      group: 'hero',
      initialValue: '台灣爸爸 Eric × 泰國媽媽 Min，深受台灣家庭信賴',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'heroDescription',
      title: 'Hero Description / 補充說明',
      type: 'text',
      group: 'hero',
      rows: 3,
      description: '補充品牌定位與服務方式。建議 1-2 句即可。',
    }),
    defineField({
      name: 'heroProofItems',
      title: 'Hero Proof Pills / 信任短句',
      type: 'array',
      group: 'hero',
      description: '首頁主視覺下方的小標籤。建議 3-4 句最有辨識度的重點。',
      of: [{ type: 'string' }],
    }),
    defineField({
      name: 'heroHelperText',
      title: 'Hero Helper Text / CTA 下方說明',
      type: 'text',
      group: 'hero',
      rows: 2,
      description: '用來降低詢問門檻，例如提醒使用者先丟日期、人數即可。',
    }),
    defineField({
      name: 'heroPanelEyebrow',
      title: 'Hero Panel Eyebrow / 側欄小標',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroPanelTitle',
      title: 'Hero Panel Title / 側欄標題',
      type: 'text',
      group: 'hero',
      rows: 2,
    }),
    defineField({
      name: 'heroPanelDescription',
      title: 'Hero Panel Description / 側欄說明',
      type: 'text',
      group: 'hero',
      rows: 3,
    }),
    defineField({
      name: 'heroPrimaryCta',
      title: 'Hero Primary CTA / 主按鈕',
      type: 'object',
      group: 'hero',
      fields: [
        defineField({
          name: 'text',
          title: 'Button Text / 按鈕文字',
          type: 'string',
          initialValue: 'LINE 詢問清邁安排',
        }),
        defineField({
          name: 'link',
          title: 'Button Link / 按鈕連結',
          type: 'url',
          initialValue: 'https://line.me/R/ti/p/@037nyuwk',
          description: '若是外部連結請填完整網址。',
        }),
      ],
    }),
    defineField({
      name: 'heroSecondaryCta',
      title: 'Hero Secondary CTA / 次按鈕',
      type: 'object',
      group: 'hero',
      fields: [
        defineField({
          name: 'text',
          title: 'Button Text / 按鈕文字',
          type: 'string',
          initialValue: '看行程案例',
        }),
        defineField({
          name: 'link',
          title: 'Button Link / 按鈕連結',
          type: 'string',
          initialValue: '/tours',
          description: '內部頁面請用相對路徑，例如 `/tours`。',
        }),
      ],
    }),

    defineField({
      name: 'whoWeAreVideoUrl',
      title: 'Brand Video URL / 品牌影片網址',
      type: 'url',
      group: 'whoWeAre',
      description: '可放 Cloudinary 或可直接播放的影片網址。',
    }),
    defineField({
      name: 'whoWeAreVideoPoster',
      title: 'Brand Video Poster / 影片封面',
      type: 'image',
      group: 'whoWeAre',
      options: { hotspot: true },
      fields: [
        defineField({
          name: 'alt',
          title: 'Alt Text / 圖片替代文字',
          type: 'string',
        }),
      ],
    }),
    defineField({
      name: 'whoWeAreVideoAspect',
      title: 'Video Aspect / 影片比例',
      type: 'string',
      group: 'whoWeAre',
      options: {
        list: [
          { title: 'Portrait 9:16', value: 'portrait' },
          { title: 'Landscape 16:9', value: 'landscape' },
          { title: 'Square 1:1', value: 'square' },
        ],
      },
      initialValue: 'portrait',
    }),
    defineField({
      name: 'whoWeAreTitle',
      title: 'Who We Are Title / 區塊標題',
      type: 'string',
      group: 'whoWeAre',
      initialValue: '爸媽開的包車，更懂帶小孩',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'whoWeAreSubtitle',
      title: 'Who We Are Subtitle / 區塊副標',
      type: 'string',
      group: 'whoWeAre',
      initialValue: '台灣爸爸 Eric × 泰國媽媽 Min',
    }),
    defineField({
      name: 'whoWeAreDescription',
      title: 'Who We Are Description / 區塊說明',
      type: 'string',
      group: 'whoWeAre',
    }),
    defineField({
      name: 'whoWeAreTrustPoints',
      title: 'Who We Are Trust Points / 信任要點',
      type: 'array',
      group: 'whoWeAre',
      description: '建議 3 點即可，避免太長。',
      of: [{ type: 'string' }],
    }),
    defineField({
      name: 'whoWeAreStoryLink',
      title: 'Story Link / 品牌故事連結',
      type: 'string',
      group: 'whoWeAre',
      initialValue: '/blog/eric-story-taiwan-to-chiang-mai',
      description: '內部文章請用相對路徑。',
    }),
    defineField({
      name: 'whoWeAreStoryLinkText',
      title: 'Story Link Text / 品牌故事按鈕文字',
      type: 'string',
      group: 'whoWeAre',
      initialValue: '看我們為什麼住在清邁',
    }),

    defineField({
      name: 'articlesSectionTitle',
      title: 'Articles Title / 文章區標題',
      type: 'string',
      group: 'articles',
      initialValue: '精選文章',
    }),
    defineField({
      name: 'articlesSectionSubtitle',
      title: 'Articles Subtitle / 文章區副標',
      type: 'string',
      group: 'articles',
      initialValue: '把清邁旅遊常見問題整理成更容易消化的內容。',
    }),
    defineField({
      name: 'articlesShowCount',
      title: 'Articles Count / 顯示數量',
      type: 'number',
      group: 'articles',
      initialValue: 3,
      validation: (Rule) => Rule.min(1).max(6),
    }),

    defineField({
      name: 'ctaEyebrow',
      title: 'CTA Eyebrow / 底部 CTA 小標',
      type: 'string',
      group: 'cta',
      initialValue: '把旅行方向先抓順',
    }),
    defineField({
      name: 'ctaTitle',
      title: 'CTA Title / 底部 CTA 標題',
      type: 'string',
      group: 'cta',
      initialValue: '讓爸媽幫你規劃親子行程',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'ctaDescription',
      title: 'CTA Description / 底部 CTA 說明',
      type: 'string',
      group: 'cta',
      initialValue: '聊聊你的想法，我們幫你安排最適合小孩的清邁旅程',
    }),
    defineField({
      name: 'ctaHelperText',
      title: 'CTA Helper Text / 底部 CTA 補充說明',
      type: 'text',
      group: 'cta',
      rows: 2,
    }),
    defineField({
      name: 'ctaPlanningTitle',
      title: 'CTA Panel Title / 側欄標題',
      type: 'string',
      group: 'cta',
      initialValue: '你會先得到這些',
    }),
    defineField({
      name: 'ctaPlanningSteps',
      title: 'CTA Planning Steps / 側欄步驟',
      type: 'array',
      group: 'cta',
      description: '右側資訊卡的步驟列表。建議 3-4 點。',
      of: [{ type: 'string' }],
    }),
    defineField({
      name: 'ctaResponseTitle',
      title: 'CTA Response Title / 回覆標題',
      type: 'string',
      group: 'cta',
      initialValue: '通常回覆時間',
    }),
    defineField({
      name: 'ctaResponseDescription',
      title: 'CTA Response Description / 回覆說明',
      type: 'text',
      group: 'cta',
      rows: 2,
    }),
    defineField({
      name: 'ctaPrimaryCta',
      title: 'CTA Primary Button / 主按鈕',
      type: 'object',
      group: 'cta',
      fields: [
        defineField({
          name: 'text',
          title: 'Button Text / 按鈕文字',
          type: 'string',
          initialValue: 'LINE 詢問清邁安排',
        }),
        defineField({
          name: 'link',
          title: 'Button Link / 按鈕連結',
          type: 'url',
          initialValue: 'https://line.me/R/ti/p/@037nyuwk',
        }),
      ],
    }),
    defineField({
      name: 'ctaSecondaryCta',
      title: 'CTA Secondary Button / 次按鈕',
      type: 'object',
      group: 'cta',
      fields: [
        defineField({
          name: 'text',
          title: 'Button Text / 按鈕文字',
          type: 'string',
        }),
        defineField({
          name: 'link',
          title: 'Button Link / 按鈕連結',
          type: 'string',
          description: '內部頁面請用相對路徑，例如 `/services/car-charter`。',
        }),
      ],
    }),
  ],
  preview: {
    prepare() {
      return {
        title: 'Landing Page / 首頁設定',
      }
    },
  },
})
